#!/bin/sh

if [ -z "${MAX_MEMORY}" ] || [ -z "${MAX_MEMORY_PER_NODE}" ] || [ -z "${DISCOVERY_URI}" ]; then
    echo "environments variables not defined"
    exit 1
fi

cat <<EOS > /opt/presto/etc/config.properties
coordinator=false
http-server.http.port=8080
query.max-memory=${MAX_MEMORY}
query.max-memory-per-node=${MAX_MEMORY_PER_NODE}
discovery.uri=${DISCOVERY_URI}
EOS
